bases:
- environments.yaml
---
repositories:
  # Kubernetes incubator repo of helm charts
  - name: "incubator"
    url: "https://charts.helm.sh/incubator"
  - name: "mongodb"
    url: "https://mongodb.github.io/helm-charts"

releases:
  - name: "mongo-community-operator"
    chart: "mongodb/community-operator"
    disableValidation: true
    namespace: {{ .Namespace }}
    version: {{ .Values.mongo_operator_chart_version | quote }}
    wait: true
    timeout: 300
