--- 
apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
  name: postgres
  namespace: infra
spec:
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  type: ClusterIP
  selector:
    app: postgres