apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-synology-provisioner
  labels:
    app: nfs-synology-provisioner
  # replace with namespace where provisioner is deployed
  namespace: infra
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nfs-synology-provisioner
  template:
    metadata:
      labels:
        app: nfs-synology-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-synology-provisioner
          image: k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: synology/nfs
            - name: NFS_SERVER
              value: 172.23.0.2
            - name: NFS_PATH
              value: /volume2/nfs1
      volumes:
        - name: nfs-client-root
          nfs:
            server: 172.23.0.2
            path: /volume2/nfs1
