---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: archivy
  namespace: apps
spec:
  dependsOn:
    - name: nfs-synology
      namespace: infra
    - name: istio
      namespace: istio-system
  interval: 1m0s
  path: ./apps/archivy
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  validation: client
  force: true