---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cotoami
  namespace: apps
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  interval: 1m0s
  path: ./apps/cotoami
  prune: true
  dependsOn:
    - name: redis-noauth
      namespace: infra
    - name: postgres
      namespace: infra
    - name: neo4j
      namespace: infra
    - name: istio-default
      namespace: istio-system
    - name: cert-manager
      namespace: infra
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  validation: client
  force: true