---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: elasticsearch
  namespace: flux-system
spec:
  dependsOn:
    - name: elasticsearch-operator
  interval: 10m0s
  path: ./infra/elasticsearch
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system