---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: elasticsearch-operator
  namespace: infra
spec:
  interval: 10m0s
  path: ./infra/elasticsearch/operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system