---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: influxdb
  namespace: infra
spec:
  dependsOn: 
    - name: nfs-local
      namespace: infra
  interval: 10m0s
  path: "./infra/influxdb"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system