---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: istio-default
  namespace: istio-system
spec:
  dependsOn:
    - name: istio-operator
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  interval: 10m0s
  path: ./istio-system/default
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system