---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: metallb
  namespace: metallb-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  interval: 10m0s
  path: ./metallb-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system