---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: neo4j
  namespace: infra
spec:
  interval: 10m0s
  path: "./infra/neo4j"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system