---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: paperless
  namespace: apps
spec:
  dependsOn:
    - name: nfs-synology
      namespace: infra
  interval: 1m0s
  path: ./apps/paperless
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  validation: client