---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: redis-noauth
  namespace: infra
spec:
  interval: 10m0s
  path: "./infra/redis-noauth"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system