---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: trilium
  namespace: apps
spec:
  dependsOn:
    - name: nfs-synology
      namespace: infra
    - name: istio
      namespace: istio-system
    - name: cert-manager
      namespace: infra
  interval: 1m0s
  path: ./apps/trilium
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  validation: client