bases:
- environments.yaml
---
repositories:
  # Kubernetes incubator repo of helm charts
  - name: "incubator"
    url: "https://charts.helm.sh/incubator"

releases:
  - name: "orientdb"
    chart: "incubator/raw"
    namespace: {{ .Namespace }}
    version: {{ .Values.k8s_raw_chart_version | quote }}
    wait: true
    timeout: 60
    values:
    - resources:
      - apiVersion: v1
        kind: PersistentVolumeClaim
        metadata:
          name: orientdb-pv-claim
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 24Gi
      - apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: orientdb
        spec:
          replicas: 1
          selector:
            matchLabels:
              application: orientdb
          template:
            metadata:
             name: orientdb
             labels:
               application: orientdb
            spec:
              containers:
                - name: orientdb
                  image: orientdb:latest
                  env:
                   - name: ORIENTDB_ROOT_PASSWORD
                     value: "rootpwd"
                  ports:
                  - containerPort: 2480
                    name: orientdb
                  volumeMounts:
                  - name: orientdb-data
                    mountPath: /data
              volumes:
                  - name: orientdb-data
                    persistentVolumeClaim:
                      claimName: orientdb-pv-claim

      - apiVersion: v1
        kind: Service
        metadata:
          name: orientdb
          labels:
            application: orientdbservice
        spec:
          type: LoadBalancer
          selector:
            application: orientdb
          ports:
           - protocol: TCP
             port: 2480
             name: http    

      