apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: sabnzbd-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: sabnzbd-http-port
      protocol: HTTP
    hosts:
      - sabnzbd.simplefxn.com
    tls:
      httpsRedirect: true
  - port:
      number: 443
      name: sabnzbd-https-port
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: sabnzbd.simplefxn.com
    hosts:
      - sabnzbd.simplefxn.com
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: sabnzbd-vs
  namespace: istio-system
spec:
  hosts:
  - "sabnzbd.simplefxn.com"
  gateways:
  - sabnzbd-gateway
  http:
  - route:
    - destination:
        host: sabnzbd.apps.svc.cluster.local
        port:
          number: 8080
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: sabnzbd
  namespace: istio-system
spec:
  host: sabnzbd.apps.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE