---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: haste
  namespace: apps  
spec:
  interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: haste-server
      version: 2.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/k8s-at-home/haste-server
      tag: latest
      pullPolicy: IfNotPresent
    service:
      main:
        enabled: true
        type: ClusterIP
        ports:
          http:
            enabled: true
            port: 7777
    podLabels: 
      app: haste
    env:
      TZ: "America/Chicago"
      # -- filepath for persistance
      STORAGE_FILEPATH: "/config"
      # -- sets backend
      STORAGE_TYPE: "file"
    persistence:
      config:
        enabled: true
        storageClass: synology
        size: 16Gi