apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: archivy-claim0
  namespace: apps
  name: archivy-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
