unifi_chart_version: "5.1.2"
k8s_raw_chart_version: "0.2.3"

unifi:
  image:
    repository: jacobalberty/unifi
    tag: latest
  env:
    TZ: America/Chicago
  service:
    main:
      type: LoadBalancer
      loadBalancerIP: 192.168.69.4
  persistence:
    data: 
      enabled: true
      mountPath: /unifi
      accessMode: ReadWriteOnce
      size: 64Gi
      retain: true
  mongodb:
    enabled: true
    architecture: standalone
    persistence:
      accessMode: ReadWriteOnce
      size: 64Gi
