---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: infra  
spec:
  interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: velero
      version: 2.29.4
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: flux-system
  values: