apiVersion: v1
stringData:
    cloud: ENC[AES256_GCM,data:qmg2h+3kj/2o/G8INtEcY9UMhxh3pj1q8EHG79VhcdcQbSpVSTrkC9dRTTDYDHDbgTDFBPKJI7Hu0bxkdTcODu7bzsKeaQVKpc2/II2f7SEIWNfUxS+y8uNqMl7inEHZC5BLNXy+DUohEMWPaht8vBhfvITw9wFTHy3m8qKzymWkbjLKqZBPIZKtAcwjvKiSOrxRJZYE6dK1S8p3IDtxwbMXjv4vpgC8s4cDokHWiboZdZFBxiLo724aqFWge6thmdbegZ+4iXYsSj4AImfy6AssRzs3p60SuKsF5/bTVZ7HVwV/i9kEjuKgTGSAPrkflhQ/hb47PAGQJAAAf5//kQUJOZVsHM5CqI2TWpv/tsDSjSebk5m6ob74UwNguqBd3tnJaXX6KUkUiw73Hv91Hg1hStLl9B1bcNhTKwYJBkgkz4QjfguRm5eW4YoB9rwuIRa8o5C6AJKMQ4fHa6dmKCi4BeYST6gDgA+BpYYvRGggxFqFt0urTg==,iv:QzpbaPZdxFHsMJzUQ9fvkoUH6yN7mX/7X8v1ybc8aAk=,tag:0Pk4/sw3fGqgmQWMbCKAJg==,type:str]
kind: Secret
metadata:
    name: azure-velero-credentials
    namespace: infra
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-04-23T17:11:25Z"
    mac: ENC[AES256_GCM,data:sIn/tHGv44MW/re5yg0j8i5ptrQ4lZ768JXWL5xDgYhgyZs1gjpccyRpRMkR7Eiec/QZIroaD5R0JpeRTUI1TUSEMa4IG2OYFd3rTyUn+RDOizjLgqJ/pIzETBU8/+lVqWQqWiPfCrwDVWpKZZ3j1hdf4DVN//eeLatxj3AjkT0=,iv:pDsQ+gJwgfPt3Y0L4jrl48vhJsxRKp3vP7HJsXHatro=,tag:uYwhWiUW/49KBFPXrTx0Hg==,type:str]
    pgp:
        - created_at: "2022-04-23T17:11:24Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAx/NiVxbkaAhAQ/+Pctbfy/PWnEy+JERwa+WMPoqlVv6CTCQHaP6IvH4geD8
            +2xyAaaBq/V61qItnz/Dne5X0K5YbUxfwL/y/7rbWxbYJY2k1GutdqpzdwuRGnsQ
            5rqx50aROGFdXYNpDYLHiT9+0xwtMvyeaGSGMkyUGlqx4TZIsfgYj+KjIgbPoSbN
            kkLWr02I9y0Sl060WN6IvVh6bn4eCNTVs9QneJvLp1EcO3EZElqUtr+uJo3X5fXs
            4/Dq+3dyv5Zm7jKM38WD8vUu/bbefOsRgbtMJL18Y4ahQbU4GvzrANAC/Bthetgm
            nZfVhmIOr13aPPXr9OnBAM6Kmqmf92Bnc/Yw1l/32oAKHk/NX7ZHZusvWpdy4b2N
            So9AqyHU13PAWPi7SFyN4zBvLakYJen7j4x6LLf0NtYAB8Kz/YXx3VOCk+J7C5Pi
            OD/siTzNwLpKcXoHDg9SYgU2GCb0g3Nsb404lTfMkNoDVTodL7FHmDdmknzExKHK
            WPOlBQvFdIPCBxxsqh+m+Wpjyv5mKYtV25357TdOpEssZFmAMHdH3lcWUJNKZKgk
            hR0PaelLFXF9iCOuo74LjovTiNtKXCq8UW/b5JELB5niyieoeQbhqe2K1qVLeV31
            jcBhY013yu112XvOKt0VqI8P1spkFMUDPwQJPpaS/DHIDTm6U0+vZw7A/qKmdCPU
            ZgEJAhB2nUROps0zFtX1qRwp1qHehhdmYv3TO/mja8WjqG8kYh1VBBvFajEtmMsC
            N0v6C2iAPAEe5mb3PbVy+FbDV82JKIkxfirLblkUw/i/9Qaf+tg2TvSam1sqh+0N
            hm9EhmxQVA==
            =jOXE
            -----END PGP MESSAGE-----
          fp: 9DC11809DD7D102342B09932C40921F65EFEF866
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
