apiVersion: v1
data:
    cloud: ENC[AES256_GCM,data:i7doDZd4wo6ZMVqoQTmLEh5fvJ8JKfZEar7YTSC+RkISnzXd+LfVTI1UDnfr4eAA04pyyL6RFUP0jiVEXoxN1ttPMVxggxcupYr5V+FAf6yF4id+1rKG4jV0PxKIb37WxySmPHP+/8nhZFCTAJRXZwq2maOKFA8i8ZTCCMI5Jinc6LzFsypUcVgBLzuxzoM8Vy4qq+hySdc5BlY99zdr4eJ8FN2wsMgVHtbEusVfzZaVH4Vpskk8EKRFc7RPdOtJ3o7Fv4GUn5Ve47arzVekeNEbvOtgOszqJm8wqjfw9o+acHXvLjL/wPU3abVAV/Kn6YqOHa7+Ykr/bMrRfH/eNhOR9M4X33gKr07npUpath/APXB68/VcPR1dnqoU/P9iGc4I2vw9zGnUOWE9VYfP11YOaYASJM2okQIQPyacvxmb+5iTN5gC/jWCMEE9a3A7+G1NacrLEQOA6ZuDrlDB1W3KCAepcVCd07T7io3x1DEOrA42qb0FBQ==,iv:MKj+ldaBouE/V8PRXnfk6WU5Ix3CMyj22bG7VJgA8jU=,tag:ruqDccFXoRUqHVKDlyWQug==,type:str]
kind: Secret
metadata:
    name: azure-velero-credentials
    namespace: infra
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-04-23T17:09:06Z"
    mac: ENC[AES256_GCM,data:TTAcE8WdSj2CETy9hKOPfq4XSolEpyJ3zL1o3uSWzghgpBfCzAaQDGUg36JnKXFAa9TqWRGl+sinY5wZDQkGLCn0uJppd24RhrxJ+yz5h8M3Jx4LKgpfucIcqfCRjrrbrZFr81UAgehruuOgDbzRplhfwtq4J9Of7x3urZGT4Og=,iv:+ZZwfhfrVbCwLCvy1JHCxgzoxuXElo+ebS+E3paPzEA=,tag:qrzrrgyiwlMgeZHZx5ROvw==,type:str]
    pgp:
        - created_at: "2022-04-23T17:09:06Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAx/NiVxbkaAhAQ/+N1+8qqPriXRbCy0vbcYejFDO44s/vEu7EXn1KyvqMIUX
            jPZHWANDuoR6GdT3RMIjwABWVm+udL2yMAMQAGhfSY6RiICzg+0y2i3iXc/58CNY
            z5LpABNQHLD+oT2/GlJBWXFHZeAnr7xIez2NepZalQhkVIu/3cBLKJr+9bgVWJY3
            wveQ1kbwZGuL7GiYbENDN04/fTZHhGOE7MSPMY44UkUWeyOAuEsHR83yqFKc7rm6
            yRBDlTd1lf0h8gSbbRgJFvBpdtXl/lbYb0WCT7Z8XK87xdDgVug99NJ+s8vAsJz/
            b1ViZGGTkqqr3D+uIH8kOMXDmyABPpLPuECJs0MfQhTIYkEDAGJnY8l98SDwHS3x
            z2kA+zXRiL4DfcwwdsWcL7yQhve042AzaGUgGGxu267iETUUxyFtC+ZAPrYPnfM6
            SIlykxYAvfWqb7OwOUQaxe/RCOlXO1Tj9CURkDPAmXtx+C8OUGE8yUd+3oFMxlN0
            bQT3W0bGtDb49bQKKvu1SAvK95rdLvaw13zqP+lUwEvsuJOKTO8PTQnAcS7YCdOM
            Oo06zF2Kzja0W/zgDXgCO2Duu4WSOKjv/DymtdODxsPAsAcIc9UZeFr0H4Xsm7Nb
            gncrlcw9rjiMJd1qpRLBn24nm5BRPaZp9mZcArpJyufb49Og5v3d+fh9Tq51wiDU
            aAEJAhAWDUPFSdu3IeGPUDX7UOY+X5J9RKjlpeW1gwo70UQTKGVfCPf+Dy5Prf8V
            EnMj3J3dzRcwuRhvR0ShsNkYMkHjKMhoR/9DEABtqoNS1lqCCDoo5/VVOodVLFax
            0gy/QUzbpQB9
            =XQDg
            -----END PGP MESSAGE-----
          fp: 9DC11809DD7D102342B09932C40921F65EFEF866
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
