apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: unifi-controller
  name: unifi-controller-tcp
  namespace: infra
  annotations:
    metallb.universe.tf/allow-shared-ip: "true"
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.69.4
  ports:
    - name: device-communication
      port: 8080
      targetPort: 8080
    - name: "8081"
      port: 8081
      targetPort: 8081
    - name: web-ui
      port: 8443
      targetPort: 8443
    - name: guest-portal-ssl
      port: 8843
      targetPort: 8843
    - name: guest-portal
      port: 8880
      targetPort: 8880
    - name: mobile-throughput
      port: 6789
      targetPort: 6789
  selector:
    app: unifi-controller
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: unifi-controller
  name: unifi-controller-udp
  namespace: infra
  annotations:
    metallb.universe.tf/allow-shared-ip: "true"
spec:
  type: LoadBalancer
  ports:
    - name: stun
      port: 3478
      protocol: UDP
      targetPort: 3478
    - name: ap-discovery
      port: 10001
      protocol: UDP
      targetPort: 10001
  loadBalancerIP: 192.168.69.4
  selector:
    app: unifi-controller
