apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: unifi-controller
  name: unifi-controller
  namespace: infra
spec:
  replicas: 1
  serviceName: unifi-controller
  selector:
    matchLabels:
      app: unifi-controller
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: unifi-controller
      annotations:
        backup.velero.io/backup-volumes: unifi-unifi,unifi-data,unifi-backup
    spec:
      containers:
        - env:
            - name: MEM_LIMIT
              value: 1024M
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
          image: jacobalberty/unifi:latest
          name: unifi-controller
          ports:
            - containerPort: 3478
              protocol: UDP
            - containerPort: 10001
              protocol: UDP
            - containerPort: 8080
            - containerPort: 8081
            - containerPort: 8443
            - containerPort: 8843
            - containerPort: 8880
            - containerPort: 6789
          volumeMounts:
            - mountPath: /unifi 
              name: unifi-unifi 
            - mountPath: /unifi/data 
              name: unifi-data 
            - mountPath: /unifi/data/backup 
              name: unifi-backup 
      restartPolicy: Always
      volumes:
        - name: unifi-unifi
          persistentVolumeClaim:
            claimName: unifi-unifi 
        - name: unifi-data 
          persistentVolumeClaim:
              claimName: unifi-data 
        - name: unifi-backup
          persistentVolumeClaim:
              claimName: unifi-backup
          

