---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cotoami
  namespace: apps
spec:
  dependsOn:
    - name: nfs-local
      namespace: infra
    - name: redis-noauth
      namespace: infra
    - name: neo4j
      namespace: infra
  interval: 1m0s
  path: ./overlays/prod/apps/cotoami
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-k8s
    namespace: flux-system
  validation: client
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg