---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: trillium
  namespace: apps
spec:
  dependsOn:
    - name: nfs-local
      namespace: infra
  interval: 1m0s
  path: ./overlays/prod/apps/trillium
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-k8s
    namespace: flux-system
  validation: client