---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: paperless
  namespace: apps  
spec:
  interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: paperless
      version: 6.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    image:
      repository: jonaswinkler/paperless-ng
      tag: 1.4.5
      pullPolicy: IfNotPresent
    service:
      main:
        enabled: true
        type: ClusterIP
        ports:
          http:
            enabled: true
            port: 8000
    podLabels: 
      app: paperless
    env:
      TZ: "America/Chicago"
      COMPOSE_PROJECT_NAME: paperless
      PAPERLESS_OCR_LANGUAGE: eng
    persistence:
      # -- Configure persistence for data.
      # @default -- See values.yaml
      data:
        enabled: true
        mountPath: /usr/src/paperless/data
        accessMode: ReadWriteOnce
        size: 64Gi
        storageClass: synology
        emptyDir:
          enabled: false
        retain: true
      # -- Configure persistence for media.
      # @default -- See values.yaml
      media:
        enabled: true
        mountPath: /usr/src/paperless/media
        accessMode: ReadWriteOnce
        size: 32Gi
        storageClass: synology
        emptyDir:
          enabled: false
        retain: true
      # -- Configure volume to monitor for new documents.
      # @default -- See values.yaml
      consume:
        enabled: true
        mountPath: /usr/src/paperless/consume
        accessMode: ReadWriteOnce
        storageClass: synology
        emptyDir:
          enabled: false
        retain: true
      # -- Configure export volume.
      # @default -- See values.yaml
      export:
        enabled: true
        mountPath: /usr/src/paperless/export
        accessMode: ReadWriteOnce
        storageClass: synology
        emptyDir:
          enabled: false
        retain: true