---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-home-assistant
  namespace: apps
spec:
  volumeMode: Filesystem
  storageClassName: local
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: apps
    name: home-assistant-config
  nfs:
    path: /var/k8s-data/apps-home-assistant-config-pvc-b0c0b050-af61-4844-9c58-4924d903d2b9
    server: 172.20.20.16