---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: trilium
  namespace: apps
spec:
  interval: 1m0s
  path: ./cluster/k8s/apps/trilium/deploy
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  validation: client
