apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: infra
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:WbmJLR9qooCGS+kr8bNwF18H0lJln+Nxcjm2DgOX8S6b6qbhIw/1Uw==,iv:0XBJb6zyqRr6fFK3m7ZWF8tOwiLyregZnsow+lRSBoo=,tag:Xa5xl4p3QLqGBFoY+4Dj/g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-08-18T17:35:13Z"
    mac: ENC[AES256_GCM,data:ULeQWvZGRXEiYg0Gd5cDperBvZZZ3t4GoISWn/7ngjWYLvEZfZT+1OSEVG+eRngd5PJ+GuO7DalDyN9tuwFUSoum8Qm5xCl6q1swjmnWLEjLNVJQyaOnNFNplbw/x4gUiN/yTcuJweTwffdOd95r++6Yfcdjrw54gYwIS6dkkFE=,iv:hIc69d5TIP/sSzPhxFwOS+at5zOSiSRyT0O+eg4LIMY=,tag:j4l2HIshjWJ29E2gEx0PUQ==,type:str]
    pgp:
        - created_at: "2021-08-18T17:35:12Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAx/NiVxbkaAhAQ//QX8RZQHoxiBRhpe05hHyTVgygDK5u+fEhGiIcmvD8Wnz
            L3z/Rc42tfYAfqWPsO8lN7J7xb2SkCaGDszJY7BgVj3y/3Lnuyv8bMSS6ffx92/b
            I4JKpVZJxA51I6RDhOFVmQdv8qCINNdVKkkWWaO5HBoX7xxtS7vgnODGTRYtK1X5
            3fyWKqDKTDoOxeoYl7vrDsE05nFXAlzUsIPWT9vd7bNo2GYPMf4+Sm/MmhnFwFo8
            gXUhd3gffnbV5v96EVEoTuwTy+cbibFTVdGt1CEcIThErD+FS21VYHbbuvPeLWUB
            Og/8WZaCMXOPoXWQH0aPR0cVMvBtNQXithKjiAyMgI299iFbO685QdByNR/i5xj3
            SBpM1DtdZSExBQNnCrpb6vuXpIGvdghENmZ9jOrsa95y6lGMcYHfVkdzylrLxm1M
            pC50xRMHi/+FUoTkEQz+wNARFRKQO5rg39bUB/MWdIST+d+LvtY3rKY6TYKFLuRx
            Syu+C1H9gVsKReZBB3jNhJjbRlR2UFZzDZA3ds+gOzxsnejpcvWpzR/lEt9kWoSy
            zA/z2Hx36kpfWkVFAKm1MaIe7ITgzEYT/XmNgfU8JfoeicOm7uw2ioeu5JDs4O5j
            mTu3HbVFGiWB4mxJakzCixnMZV6RGYvPBO1pHI5Od7vVx+alt3HPhOiOGr3xvMrU
            ZgEJAhVxkc4LpkMgZ+N3/5GdbTcXP3yrjIO8edvgRoyFQLmvGB3xq91ufYqV1H/N
            HNNrEb2RZTywvXafSxnwWPd7mGSw7PL9TxS1MSXBcH9KPlLoBoYCWA8auQEpjc+j
            ZrLWnuCeCg==
            =o7k2
            -----END PGP MESSAGE-----
          fp: 9DC11809DD7D102342B09932C40921F65EFEF866
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
