apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: harbor.simplefxn.com
  namespace: infra
spec:
  secretName: harbor.simplefxn.com
  subject:
    organizations:
    - SimpleFxn
  commonName: "*.simplefxn.com"
  dnsNames:
  - "*.simplefxn.com"
  issuerRef:
    name: simplefxn-issuer
    kind: ClusterIssuer