apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: trilium
  name: trilium
  namespace: apps
spec:
  storageClassName: local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
