apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kibana.simplefxn.com
  namespace: istio-system
spec:
  secretName: kibana.simplefxn.com
  subject:
    organizations:
    - SimpleFxn 
  commonName: kibana.simplefxn.com
  dnsNames:
  - kibana.simplefxn.com
  issuerRef:
    name: simplefxn-issuer
    kind: ClusterIssuer