---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: simplefxn-issuer
  namespace: infra
spec:
  acme:
    email: marcelo@voidspace.us
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: simplefxn-issuer-account-key
    solvers:
    - dns01:
        cloudflare:
          email: marcelo@voidspace.us
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
---