apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: home-assistant-tls
  namespace: apps
spec:
  secretName: home-assistant-tls
  subject:
    organizations:
    - SimpleFxn
  commonName: home-assistant.simplefxn.com
  dnsNames:
  - home-assistant.simplefxn.com
  - hass.simplefxn.com
  issuerRef:
    name: simplefxn-issuer
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: node-red-tls
  namespace: apps
spec:
  secretName: node-red-tls
  subject:
    organizations:
    - SimpleFxn
  commonName: node-red.simplefxn.com
  dnsNames:
  - node-red.simplefxn.com
  issuerRef:
    name: simplefxn-issuer
    kind: ClusterIssuer
