apiVersion: v1
kind: ConfigMap
metadata:
  name: frigate-config
  namespace: apps
data:
  config.yml: |
    cameras:
      back:
        ffmpeg:
          inputs:
            - path: rtsp://axis:Ike0cuso@172.23.0.184/onvif-media/media.amp
              roles:
                - detect
                - rtmp