apiVersion: v1
kind: ConfigMap
metadata:
  name: frigate-config
  namespace: apps
data:
  config.yml: |
    mqtt:
      host: mosquitto.infra.svc.cluster.local
      port: 1883
      topic_prefix: frigate
      client_id: frigate
    cameras:
      front_right_camera:
        ffmpeg:
          inputs:
            - path: rtsp://axis:Ike0cuso@172.23.0.184/onvif-media/media.amp
              roles:
                - detect
                - rtmp
                - record
      front_left_camera:
        ffmpeg:
          inputs:
            - path: rtsp://axis:Ike0cuso@172.23.0.185/onvif-media/media.amp
              roles:
                - detect
                - rtmp
                - record
      pool_camera:
        ffmpeg:
          inputs:
            - path: rtsp://axis:Ike0cuso@172.23.0.186/onvif-media/media.amp
              roles:
                - detect
                - rtmp
                - record
    record:
      enabled: True
      events:
        retain:
          default: 120
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: True
      retain:
        default: 60
    objects:
      track:
        - person
        - car
        - motorcycle
        - bird
        - cat
        - dog

