apiVersion: v1
kind: ConfigMap
metadata:
  name: frigate-config
  namespace: apps
data:
  config.yml: |
    mqtt:
      host: mosquitto.infra.svc.cluster.local
      port: 1883
      topic_prefix: frigate
      client_id: frigate
    cameras:
      back:
        ffmpeg:
          inputs:
            - path: rtsp://axis:Ike0cuso@172.23.0.184/onvif-media/media.amp
              roles:
                - detect
                - rtmp
                - record
    record:
      enabled: True
      expire_interval: 60
      retain:
        days: 120
        mode: all
      events:
        retain:
          default: 120
          mode: motion
          objects:
            person: 15
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: True
      retain:
        default: 60
