apiVersion: v1
kind: ConfigMap
metadata:
  name: frigate-config
  namespace: apps
data:
  config.yml: |
    mqtt:
      host: mosquitto.infra.svc.cluster.local
      port: 1883
      topic_prefix: frigate
      client_id: frigate
    go2rtc:
      streams:
        livingroom:
          - rtsp://frigate:baTkiv-toxbin-1sovsi@172.23.0.25:554//h264Preview_01_main
    cameras:
      living_room:
        ffmpeg:
          output_args:
            record: preset-record-generic-audio-copy
          inputs:
            - path: rtsp://127.0.0.1:8554/livingroom 
              input_args: preset-rtsp-restream
              roles:
                - record
                - detect
      front_door:
        ffmpeg:
          inputs:
            - path: rtsp://axis:Ike0cuso@172.23.0.184/onvif-media/media.amp?profile=profile_1_h264
              roles:
                - record
            - path: rtsp://axis:Ike0cuso@172.23.0.184/onvif-media/media.amp?profile=rtmp
              roles:
                - rtmp
            - path: rtsp://axis:Ike0cuso@172.23.0.184/onvif-media/media.amp?profile=detect
              roles:
                - detect
        zones:
          door:
            coordinates: 386,523,352,634,0,462,0,226
            objects:
              - person
              - cat
              - dog
              - bird
          front_yard:
            coordinates: 233,234,401,53,623,0,872,0,1118,0,1280,61,1280,720,890,720,574,699,344,638,420,446,233,264
            objects:
              - person
              - cat
              - dog
              - bird
        record:
          events:
            required_zones:
              - door
              - front_yard
        snapshots:
          required_zones:
            - door
            - front_yard
      garage:
        ffmpeg:
          inputs:
            - path: rtsp://axis:Ike0cuso@172.23.0.185/onvif-media/media.amp?profile=profile_1_h264
              roles:
                - record
            - path: rtsp://axis:Ike0cuso@172.23.0.185/onvif-media/media.amp?profile=rtmp
              roles:
                - rtmp
            - path: rtsp://axis:Ike0cuso@172.23.0.185/onvif-media/media.amp?profile=detect
              roles:
                - detect
        record:
          events:
            required_zones:
              - driveway
              - street
        snapshots:
          required_zones:
            - driveway
            - street
        zones:
          driveway:
            coordinates: 108,362,74,720,884,720,808,410,748,241,695,116,316,102
            objects:
              - person
              - bird
              - cat
              - dog
          street:
            coordinates: 0,151,275,108,691,119,993,171,1256,333,1248,283,996,85,888,48,648,44,445,30,181,49,0,81
            objects:
              - car
              - person
              - bird
              - cat
              - dog
      pool:
        ffmpeg:
          inputs:
            - path: rtsp://axis:Ike0cuso@172.23.0.186/onvif-media/media.amp
              roles:
                - detect
                - rtmp
                - record
        zones:
          pool_zone:
            coordinates: 241,720,1280,720,1280,138,628,106,369,152,221,187,79,233,149,462
            objects:
              - person
              - cat
              - bird
              - dog
        record:
          events:
            required_zones:
              - pool_zone
        snapshots:
          required_zones:
            - pool_zone
    record:
      enabled: True
      events:
        retain:
          default: 120
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: True
      retain:
        default: 60
    objects:
      track:
        - person
        - car
        - motorcycle
        - bird
        - cat
        - dog
    detectors:
      cpu1:
        type: cpu
        num_threads: 3
      cpu2:
        type: cpu
        num_threads: 3
      cpu3:
        type: cpu
        num_threads: 3
      cpu4:
        type: cpu
        num_threads: 3
