apiVersion: v1
kind: ConfigMap
metadata:
  name: frigate-config
  namespace: apps
data:
  config.yml: |
    mqtt:
      host: mosquitto.infra.svc.cluster.local
      port: 1883
      topic_prefix: frigate
      client_id: frigate
    cameras:
      garage:
        ffmpeg:
          inputs:
            - path: rtsp://axis:Ike0cuso@172.23.0.184/onvif-media/media.amp?profile=profile_1_h264
              roles:
                - record
            - path: rtsp://axis:Ike0cuso@172.23.0.184/onvif-media/media.amp?profile=rtmp
              roles:
                - rtmp
            - path: rtsp://axis:Ike0cuso@172.23.0.184/onvif-media/media.amp?profile=detect
              roles:
                - detect
        record:
          events:
            required_zones:
              - driveway
              - street
        snapshots:
          required_zones:
            - driveway
            - street
        zones:
          driveway:
            coordinates: 108,362,74,720,884,720,808,410,748,241,695,116,316,102
            objects:
              - person
              - bird
              - cat
              - dog
          street:
            coordinates: 0,151,275,108,691,119,993,171,1256,333,1248,283,996,85,888,48,648,44,445,30,181,49,0,81
            objects:
              - car
              - person
              - bird
              - cat
              - dog
      front_door:
        ffmpeg:
          inputs:
            - path: rtsp://axis:Ike0cuso@172.23.0.185/onvif-media/media.amp?profile=profile_1_h264
              roles:
                - record
            - path: rtsp://axis:Ike0cuso@172.23.0.185/onvif-media/media.amp?profile=rtmp
              roles:
                - rtmp
            - path: rtsp://axis:Ike0cuso@172.23.0.185/onvif-media/media.amp?profile=detect
              roles:
                - detect
      pool:
        ffmpeg:
          inputs:
            - path: rtsp://axis:Ike0cuso@172.23.0.186/onvif-media/media.amp
              roles:
                - detect
                - rtmp
                - record
    
    record:
      enabled: True
      events:
        retain:
          default: 120
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: True
      retain:
        default: 60
    objects:
      track:
        - person
        - car
        - motorcycle
        - bird
        - cat
        - dog
    detectors:
      cpu1:
        type: cpu
        num_threads: 3
      cpu2:
        type: cpu
        num_threads: 3
      cpu3:
        type: cpu
        num_threads: 3
      cpu4:
        type: cpu
        num_threads: 3
