apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: home-assistant
  namespace: apps
  name: home-assistant-config
spec:
  storageClassName: local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: home-assistant
  namespace: apps
  name: home-assistant-backup
spec:
  storageClassName: local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: home-assistant
  namespace: apps
  name: home-assistant-media
spec:
  storageClassName: local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi