apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cryptpad
  name: cryptpad
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cryptpad
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cryptpad
      annotations:
        backup.velero.io/backup-volumes: cryptpad
    spec:
      containers:
        - env:
            - name: CPAD_MAIN_DOMAIN
              value: cryptpad.simplefxn.com
            - name: CPAD_SANDBOX_DOMAIN
              value: sandbox.simplefxn.com
            - name: CPAD_HTTP2_DISABLE
              value: "true"
            - name: CPAD_TRUSTED_PROXY
              value: 10.0.0.0/8
            - name: CPAD_REALIP_RECURSIVE
              value: "on"
            - name: CPAD_REALIP_HEADER
              value: X-Forwarded-For
          image: promasu/cryptpad:nginx-alpine
          name: cryptpad
          ports:
            - containerPort: 80
          resources: {}
          volumeMounts:
            - mountPath: /cryptpad/blob
              name: cryptpad-blob
            - mountPath: /cryptpad/block
              name: cryptpad-block
            - mountPath: /cryptpad/customize
              name: cryptpad-customize
            - mountPath: /cryptpad/data
              name: cryptpad-data
            - mountPath: /cryptpad/datastore
              name: cryptpad-datastore
            - mountPath: /cryptpad/config
              name: cryptpad-config
      restartPolicy: Always
      volumes:
        - name: cryptpad-blob
          persistentVolumeClaim:
            claimName: cryptpad-blob
        - name: cryptpad-block
          persistentVolumeClaim:
            claimName: cryptpad-block
        - name: cryptpad-customize
          persistentVolumeClaim:
            claimName: cryptpad-customize
        - name: cryptpad-data
          persistentVolumeClaim:
            claimName: cryptpad-data
        - name: cryptpad-datastore
          persistentVolumeClaim:
            claimName: cryptpad-datastore
        - name: cryptpad-config
          configMap:
            name: cryptpad-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: cryptopad
  name: cryptpad-blob
  namespace: apps
spec:
  storageClassName: synology
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: cryptopad
  name: cryptpad-block
  namespace: apps
spec:
  storageClassName: synology
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: cryptopad
  name: cryptpad-customize
  namespace: apps
spec:
  storageClassName: synology
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: cryptopad
  name: cryptpad-data
  namespace: apps
spec:
  storageClassName: synology
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: cryptopad
  name: cryptpad-datastore
  namespace: apps
spec:
  storageClassName: synology
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: cryptpad
  name: cryptpad
  namespace: apps
spec:
  ports:
    - name: "cryptopad-80"
      port: 80
      targetPort: 80
  selector:
    app: cryptpad
