---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- trilium-deployment.yaml
- trilium-persistentvolumeclaim.yaml
- trilium-service.yaml
- certificate.yaml
- ingress-gateway.yaml
