apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
      interval: 1m
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    kubeControllerManager:
      service:
        port: 10257 # https port
        targetPort: 10257
      serviceMonitor:
        https: true # use https
        insecureSkipVerify: true # accept self-signed certificate
        serverName: 127.0.0.1 # do not search for called ip, but 127.0.0.1 as CN in certificate
    kubeScheduler:
      service:
        port: 10259
        targetPort: 10259
      serviceMonitor:
        https: true
        insecureSkipVerify: true
    prometheusOperator:
      hostNetwork: true
      tls:
        internalPort: 10253
    kubeEtcd:
      serviceMonitor:
        scheme: https
        insecureSkipVerify: false
        serverName: localhost
        caFile: /etc/prometheus/secrets/etcd-client-cert/ca.crt
        certFile: /etc/prometheus/secrets/etcd-client-cert/healthcheck-client.crt
        keyFile: /etc/prometheus/secrets/etcd-client-cert/healthcheck-client.key
    alertmanager:
      enabled: false
      alertmanagerSpec:
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: local
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 16Gi
    grafana:
      sidecar:
        dashboards:
          searchNamespace: ALL
    prometheus:
      prometheusSpec:
        secrets: ['etcd-client-cert']
        additionalScrapeConfigs:
          - job_name: kubernetes-apiserver
            kubernetes_sd_configs:
            - role: endpoints
              namespaces:
                names:
                  - default
            scheme: https
            tls_config:
              ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
              insecure_skip_verify: true
            bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
            relabel_configs:
            - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
              action: keep
              regex: kubernetes;https
          # Kubernetes pods
          - job_name: kubernetes-pods
            kubernetes_sd_configs:
            - role: pod
            relabel_configs:
            - action: keep
              regex: true
              source_labels:
              - __meta_kubernetes_pod_annotation_prometheus_io_scrape
            - action: replace
              regex: (.+)
              source_labels:
              - __meta_kubernetes_pod_annotation_prometheus_io_path
              target_label: __metrics_path__
            - action: replace
              regex: ([^:]+)(?::\d+)?;(\d+)
              replacement: $1:$2
              source_labels:
              - __address__
              - __meta_kubernetes_pod_annotation_prometheus_io_port
              target_label: __address__
            - action: labelmap
              regex: __meta_kubernetes_pod_label_(.+)
            - action: replace
              source_labels:
              - __meta_kubernetes_namespace
              target_label: namespace
            - action: replace
              source_labels:
              - __meta_kubernetes_pod_name
              target_label: pod
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: local 
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 128Gi
        podMonitorSelector:
          matchLabels:
            app.kubernetes.io/part-of: flux
        