apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - namespace.yaml
  - repository.yaml
  - account.yaml
  - rbac.yaml
  - release.yaml
  - flux-podmonitor.yaml
configMapGenerator:
  - name: prometheus-config
    files:
      - prometheus.yaml