bases:
- environments.yaml
---
repositories:
  # Kubernetes incubator repo of helm charts
  - name: "incubator"
    url: "https://charts.helm.sh/incubator"

releases:
  - name: "meemo"
    chart: "incubator/raw"
    namespace: {{ .Namespace }}
    version: {{ .Values.k8s_raw_chart_version | quote }}
    wait: true
    timeout: 60
    values:
    - resources:
      - apiVersion: v1
        kind: PersistentVolumeClaim
        metadata:
          name: meemo-data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
      - apiVersion: v1
        kind: Service
        metadata:
          name: meemo-service
        spec:
          selector:
            application: meemo
          type: LoadBalancer
          ports:
          - name: meemo-service-port
            protocol: TCP
            port: 80
            targetPort:  meemo-web-svc

      - apiVersion: apps/v1
        kind: Deployment
        metadata:
          annotations:
            component: meemo
          creationTimestamp: null
          labels:
            application: meemo
          name: meemo
        spec:
          replicas: 1
          selector:
            matchLabels:
              application: meemo
          strategy:
            type: Recreate
          template:
            metadata:
              annotations:
                component: meemo
              creationTimestamp: null
              labels:
                application: meemo
            spec:
              imagePullSecrets: 
                - name: reg-cred-secret
              containers:
                - name: meemo
                  image: registry.simplefxn.com:5000/meemo:v1.17.1
                  imagePullPolicy: Always
                  ports:
                    - containerPort: 3000
                      protocol: TCP
                      name: meemo-web-svc
                  resources: {}
                  env:
                    - name: MONGO_USERNAME
                      valueFrom:
                        secretKeyRef:
                          name: mongodb-admin-admin
                          key: username
                    - name: MONGO_PASSWORD
                      valueFrom:
                        secretKeyRef:
                          name: mongodb-admin-admin
                          key: password
                    - name: PORT
                      value: "3000"
                    - name: "BIND_ADDRESS"
                      value: "0.0.0.0"
                    - name: "CLOUDRON_MONGODB_URL"
                      value: "mongodb://$(MONGO_USERNAME):$(MONGO_PASSWORD)@mongodb-svc.default.svc.cluster.local:27017/meemo?authSource=admin"
                    - name: "NODE_ENV"
                      value: "production"
                    - name: "CLOUDRON_LOCAL_AUTH_FILE"
                      value: "/data/users.json"
                    - name: "LOCAL_AUTH_FILE"
                      value: "/data/users.json"
                    - name: "CLOUDRON_APP_ORIGIN"
                      value: "http://notes.simplefxn.com"
                  volumeMounts: 
                    - name: meemo-data-volume
                      mountPath: /data
              volumes:
                - name: meemo-data-volume
                  persistentVolumeClaim:
                    claimName: meemo-data
              restartPolicy: Always

    