bases:
- environments.yaml
---
repositories:
  # Kubernetes incubator repo of helm charts
  - name: "incubator"
    url: "https://charts.helm.sh/incubator"
  - name: "mongodb"
    url: "https://mongodb.github.io/helm-charts"

releases:
  - name: "mongo-community-operator"
    chart: "mongodb/community-operator"
    disableValidation: true
    namespace: {{ .Namespace }}
    version: {{ .Values.mongo_operator_chart_version | quote }}
    wait: true
    timeout: 300
  - name: "meemo-mongodb"
    chart: "incubator/raw"
    namespace: {{ .Namespace }}
    version: {{ .Values.k8s_raw_chart_version | quote }}
    wait: true
    timeout: 60
    needs:
      - "mongo-community-operator"
    values:
    - resources:
      - apiVersion: mongodbcommunity.mongodb.com/v1
        kind: MongoDBCommunity
        metadata:
          name: example-mongodb
        spec:
          members: 3
          type: ReplicaSet
          version: "4.2.6"
          security:
            authentication:
              modes: ["SCRAM"]
          users:
            - name: my-user
              db: admin
              passwordSecretRef: # a reference to the secret that will be used to generate the user's password
                name: my-user-password
              roles:
                - name: clusterAdmin
                  db: admin
                - name: userAdminAnyDatabase
                  db: admin
              scramCredentialsSecretName: my-scram
          additionalMongodConfig:
            storage.wiredTiger.engineConfig.journalCompressor: zlib

      # the user credentials will be generated from this secret
      # once the credentials are generated, this secret is no longer required
  - name: "meemo-mongodb-secret"
    chart: "incubator/raw"
    namespace: {{ .Namespace }}
    version: {{ .Values.k8s_raw_chart_version | quote }}
    wait: true
    timeout: 60
    needs:
      - "mongo-community-operator"
    values:
    - resources:
      - apiVersion: v1
        kind: Secret
        metadata:
          name: my-user-password
        type: Opaque
        stringData:
          password: <your-password-here>
  - name: "meemo"
    chart: "incubator/raw"
    namespace: {{ .Namespace }}
    version: {{ .Values.k8s_raw_chart_version | quote }}
    wait: true
    timeout: 60
    needs:
      - "meemo-mongodb-secret"
      - "meemo-mongodb"
    values:
    - resources:
      - apiVersion: apps/v1
        kind: Deployment
        metadata:
          annotations:
            component: meemo
          creationTimestamp: null
          labels:
            io.kompose.service: meemo
          name: meemo
        spec:
          replicas: 1
          selector:
            matchLabels:
              io.kompose.service: meemo
          strategy:
            type: Recreate
          template:
            metadata:
              annotations:
                component: meemo
              creationTimestamp: null
              labels:
                io.kompose.service: meemo
            spec:
              imagePullSecrets: 
                - name: reg-cred-secret
              containers:
                - name: meemo
                  image: registry.simplefxn.com:5000/meemo:latest
                  ports:
                    - containerPort: 3000
                      protocol: TCP
                  resources: {}
                  env:
                    - name: meemo_WEB_ADDRESS
                      value: "0.0.0.0:80"
                    

              restartPolicy: Always

    