---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: nfs-local
  namespace: infra
spec:
  interval: 1m0s
  path: ./cluster/infra/nfs-local
  prune: true
  validation: client
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system