apiVersion: v1
kind: Service
metadata:
  labels:
    app: archivy-elasticsearch
  name: archivy-elasticsearch
  namespace: apps
spec:
  ports:
    - name: "tcp"
      port: 9200
      targetPort: 9200
  selector:
    app: archivy-elasticsearch