apiVersion: v1
kind: Secret
metadata:
    name: influx-auth
    namespace: infra
type: kubernetes.io/service-account-token
data:
    #ENC[AES256_GCM,data:Ofnr1BtzS7l/J2TMpLZib9BYpvcxiR+u0qytYLooizjrJ5JBs1qrRDXLsFNrMSeVbhMIl3t85pvWSthneFcf9ckjszuRsfj6fA==,iv:BCZ0ptodfPZn2Q6JO7AzjYRjg8kRsl5emCjuW+6Ugkk=,tag:CXnIy1nMx5TZWc5x09I47Q==,type:comment]
    auth.admin.password: ENC[AES256_GCM,data:ud0R+xQSNeTWQCQXWTSRGw==,iv:lKzDTcovt8wV2oaPiPEUls3nDtzYLash3hVvnEMVavg=,tag:jxSkLYxtURDu0jqZ5Bx/IA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-12-12T03:49:57Z"
    mac: ENC[AES256_GCM,data:dvQ4G42d3AwKxfk0mDfiQTNokZrQY+cL+G9YKf6K1MMjxALqvt4AGY7lBjMMApFt7n8IeM7zo1TTg3O7sAxe3NHop2rr/UGKc7xodfn2xUAiTMxaK1HyT8mqk8wgT+HFc1wbTuvIjDPJCBlveu7Vr7Fz4P28ByfdqcS1XcC1yLw=,iv:o2AZHZSj/VitY+lNNRbKSJ5MlXGqQsjaMtPzKWEdgbY=,tag:8RDPrIgZ9RCtQQeQEp7bSg==,type:str]
    pgp:
        - created_at: "2021-12-12T03:49:56Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAx/NiVxbkaAhAQ//XY1eoiKuXoWPXvc5H9CyELrCk/djSKbGGhkeJgn4cjOG
            1PBE6P8zegNF195jPGf5JiUHByn0XvpJ+j4cCfK1HNNSnecnkEmk4LpaJwVGJBk+
            7r5a8/gYaQ2GPkZrahGgCOmm1BSK/FHI8r0H4YLjJ8lkdXhoKSSv2I368WlRImAs
            lDYIZx0FQDOFRoCtxNJGPrVfknJogjV3x+Z/fvT5RKQmFQkWRidcpILJeiYCv/NR
            WT0m5iLIlUzcjzYJz9LYMIvjZc4OY7pUNTb4CjLFA+ZqPHSI1q3yUkRgfqL399zF
            gedc2ZIiAeztvCEhIJzG2CLkNsJMGG5IY+bPvaX76CJSAcMaCMrjThmbyfgZmfSd
            r8YproySOXTpyHFmIbS+Yyc0KRM+EAwdtIeE9OdG/KCEJLlXVIuj9J2kQZ1y9EOb
            k7vZEU+X99mUjjO0Z4rsJSU3SKqlMyWfwLeon+LFQD6mV/Rr1u/iBK8QKCB4G7Zf
            44lF9LnIErwADdQu5JWKZx8ietjxNKUtW02PVdw7DEn8zgvfSY26cTRTrwwK47ft
            5HGrmdiBxbyT/pm48KRxcgqgHdnGEmlsHVv5PRvwzYb4mw1izIrjnKugnuEGyIJG
            C3lNJ4Do4wBiBBgD3T0BfEh9aeCcpPNv7WbZQbH1xoP16bmKAmH4tcSzKCPiD6fU
            aAEJAhUtiK/lRtnsr1rrqxq4+FjpkcQndxNuO4C82JXsZYCvL3WEXSZQJQxtgYE+
            9o0rPf3AVl6ZPRuD50LuW8j7rtKXPpw95nToF2GSBmY2SpYCEK0wTeeMRYhUp5ze
            bQrs05b7mj6I
            =pxqU
            -----END PGP MESSAGE-----
          fp: 9DC11809DD7D102342B09932C40921F65EFEF866
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
