apiVersion: v1
kind: ConfigMap
metadata:
    name: vuegraf-configs
    namespace: apps
data:
    # Replace influx db configuration; emporia account information
    # and channel names
    vuegraf.json: |
        {
          "influxDb": {
            "version": 2,
            "url": "http://influxdb.infra.svc.cluster.local:8086",
            "org": "simplefxn",
            "bucket": "vuegraf",
            "token": "lfgmnUbyo29RQIDsBrmeRnfcZ1EHbpACs-FVEVXdGdfHfDlqfSxBxjTc0mhvpQzMR_omHlXmkQPbXOnwxwk1KQ==",
            "reset": false
          },
          "accounts": [
            {
              "name": "Ketelburg",
              "email": "marcelo@voidspace.us",
              "password": "dUBWXF7gmsjRswp71Ps4",
              "devices": [
                {
                  "name": "Left",
                  "channels": [
                    "Family",
                    "Kitchen buttler",
                    "Dinning",
                    "Dryer",
                    "Dryer",
                    "Garage",
                    "Refrigerator",
                    "Washer"
                  ]
                },
                {
                  "name": "Right",
                  "channels": [
                    "Mediaroom",
                    "Study",
                    "Furnace",
                    "Furnace",
                    "AC",
                    "AC",
                    "AC",
                    "AC"
                  ]
                }
              ]
            }
          ]
        }
