---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: neo4j
  namespace: infra
spec:
  dependsOn: 
    - name: nfs-synology
      namespace: infra
    - name: istio
      namespace: istio-system
  interval: 10m0s
  path: "./infra/neo4j"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system