apiVersion: v1
data:
  gateway.dev.knative-dev-gateway: "simplefxn-ingressgateway.dev.svc.cluster.local"
kind: ConfigMap
metadata:
  labels:
    networking.knative.dev/ingress-provider: istio
    serving.knative.dev/release: v0.25.0
  name: config-istio
  namespace: knative