apiVersion: v1
data:
  simplefxn.com: ""
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/part-of: knative-serving
    app.kubernetes.io/version: 0.25.0
    serving.knative.dev/release: v0.25.0
  name: config-domain
  namespace: knative
