apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - dev-resources.yaml
  - config-network.yaml
  - config-domain.yaml
  - config-istio.yaml
  - serving.yaml
 # - serving-nscert.yaml
  - certmanager-controller.yaml
  - eventing.yaml