apiVersion: v1
kind: ConfigMap
metadata:
    name: vuegraf-configs
    namespace: apps
data:
    # Replace influx db configuration; emporia account information
    # and channel names
    vuegraf.json: |
        {
          "influxDb": {
            "host": "influxdb-v1.infra.svc.cluster.local",
            "port": 8086,
            "user": "admin",
            "pass": "pass123!",
            "database": "vue",
            "reset": false
          },
          "accounts": [
            {
              "name": "Ketelburg",
              "email": "marcelo@voidspace.us",
              "password": "dUBWXF7gmsjRswp71Ps4",
              "devices": [
                {
                  "name": "Left",
                  "channels": [
                    "Family",
                    "Kitchen buttler",
                    "Dinning",
                    "Dryer",
                    "Dryer",
                    "Garage",
                    "Refrigerator",
                    "Washer"
                  ]
                },
                {
                  "name": "Right",
                  "channels": [
                    "Mediaroom",
                    "Study",
                    "Furnace",
                    "Furnace",
                    "AC",
                    "AC",
                    "AC",
                    "AC"
                  ]
                }
              ]
            }
          ]
        }
