# ref. https://kubernetes.io/docs/tasks/run-application/run-single-instance-stateful-application/

#
# Neo4j http service
#
apiVersion: v1
kind: Service
metadata:
  name: neo4j-http
  namespace: infra
spec:
  selector:
    app: neo4j-noauth
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 7474
    targetPort: 7474
---
#
# Neo4j bolt service
#
apiVersion: v1
kind: Service
metadata:
  name: neo4j-bolt
  namespace: infra
spec:
  selector:
    app: neo4j-noauth
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 7687
    targetPort: 7687
---
#
# Neo4j deployment
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j-noauth
  namespace: infra
  labels:
    app: neo4j-noauth
spec:
  selector:
    matchLabels:
      app: neo4j-noauth
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: neo4j-noauth
    spec:
      containers:
      - name: neo4j-noauth
        image: neo4j:3.2.5
        resources:
          requests:
            memory: 1200Mi
        ports:
        - containerPort: 7474
        - containerPort: 7687
        volumeMounts:
        - name: data-volume
          mountPath: /data
        env:
        - name: NEO4J_AUTH
          value: none
        - name: NEO4J_dbms_memory_heap_maxSize
          value: "1024m"
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: neo4j-noauth-volume-claim