apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grocy.simplefxn.com
  namespace: istio-system
spec:
  secretName: grocy.simplefxn.com
  subject:
    organizations:
    - SimpleFxn
  commonName: grocy.simplefxn.com
  dnsNames:
  - grocy.simplefxn.com
  issuerRef:
    name: simplefxn-issuer
    kind: ClusterIssuer