apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  namespace: infra
spec:
  type: ClusterIP
  selector:
    name: mosquitto
  ports:
    - name: mqtt1883
      protocol: TCP
      port: 1883
      targetPort: 1883
    - name: mqtt9001
      protocol: TCP
      port: 9001
      targetPort: 9001