---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cert-manager
  namespace: infra
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  interval: 10m0s
  path: ./overlay/prod/infra/apps/cert-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-k8s
    namespace: flux-system