---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: harbor
  namespace: harbor
spec:
  dependsOn:
    - name: nfs-synology
      namespace: infra
  interval: 10m0s
  path: ./overlays/prod/infra/apps/harbor
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-k8s
    namespace: flux-system