---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: influxdb-v1
  namespace: infra
spec:
  dependsOn:
    - name: metallb
      namespace: metallb-system
    - name: nfs-synology
      namespace: infra
  interval: 10m0s
  path: ./overlays/prod/infra/apps/influxdbV1
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-k8s
    namespace: flux-system