---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: istio-operator
  namespace: istio-operator
spec:
  dependsOn:
    - name: metallb
      namespace: metallb-system
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  interval: 10m0s
  path: ./overlays/prod/infra/apps/istio-system/operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-k8s
    namespace: flux-system