---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kafka
  namespace: kafka
spec:
  dependsOn:
    - name: istio-operator
      namespace: istio-operator
    - name: metallb
      namespace: metallb-system
    - name: strimzi-cluster-operator
      namespace: kafka
    - name: strimzi-topic-operator
      namespace: kafka
    - name: strimzi-user-operator
      namespace: kafka
  interval: 10m0s
  path: ./overlays/prod/infra/apps/kafka
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-k8s
    namespace: flux-system