---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kafka-cluster
  namespace: kafka
spec:
  dependsOn:
    - name: istio-operator
      namespace: istio-operator
    - name: metallb
      namespace: metallb-system
  interval: 10m0s
  path: ./overlays/prod/infra/apps/strimzi-0.26.1/cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-k8s
    namespace: flux-system