---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: metrics
  namespace: infra
spec:
  dependsOn: 
    - name: nfs-synology
      namespace: infra
    - name: cert-manager
      namespace: infra
  interval: 10m0s
  path: ./overlays/prod/infra/apps/metrics
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-k8s
    namespace: flux-system