---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: neo4j
  namespace: infra
spec:
  dependsOn: 
    - name: nfs-local
      namespace: infra
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  interval: 10m0s
  path: ./overlays/prod/infra/apps/neo4j
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-k8s
    namespace: flux-system