---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: loki
  namespace: infra
spec:
  dependsOn:
    - name: nfs-synology
      namespace: infra
    - name: loki
      namespace: infra
  interval: 10m0s
  path: ./overlays/prod/infra/apps/promtail
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-k8s
    namespace: flux-system