---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: redis-cluster
  namespace: infra
spec:
  dependsOn:
    - name: nfs-local
      namespace: infra
  interval: 10m0s
  path: ./overlays/prod/infra/apps/redis-cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-k8s
    namespace: flux-system