---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: unifi
  namespace: infra
spec:
  dependsOn:
    - name: metallb
      namespace: metallb-system
  interval: 10m0s
  path: ./overlays/prod/infra/apps/unifi
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-k8s
    namespace: flux-system