apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: node-red
  namespace: apps
  name: node-red-data
spec:
  storageClassName: local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
