apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: trilium
  name: trilium
  namespace: apps
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    app: trilium
