
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: home-assistant
  namespace: apps
  name: home-assistant-config
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local
  volumeMode: Filesystem 
  volumeName: pvc-home-assistant
  resources:
    requests:
      storage: 8Gi