---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: node-red
  namespace: apps
  name: node-red-data
spec:
  storageClassName: local
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem 
  volumeName: pvc-9a747ae2-a5dc-48d4-920c-ac66bc03f35e
  resources:
    requests:
      storage: 8Gi
