---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: kube-prometheus-stack
      version: 16.2.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: monitoring
  values: