loki_chart_version: "2.9.9"
k8s_raw_chart_version: "0.2.3"

loki:
  extraScrapeConfigs:
    - job_name: syslog
      syslog:
        listen_address: 0.0.0.0:1514
        labels:
          job: "syslog"
      relabel_configs:
        - source_labels: ['__syslog_message_hostname']
          target_label: 'host'
syslogService:
  enabled: true
  type: LoadBalancer
  port: 1514

