# Create InfluxDB
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb-v1
  namespace: infra
  labels:
    app: influxdb-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb-v1
  template:
    metadata:
      labels:
        app: influxdb-v1
    spec:
      containers:
      - name: influxdb-v1
        image: influxdb:1.8
        ports:
        - containerPort: 8086
        env:
#Fill with own settings
        - name: INFLUXDB_DB
          value: maindb
        - name: INFLUXDB_HTTP_AUTH_ENABLED
          value: 'true'
        - name: INFLUXDB_ADMIN_USER
          value: admin
        - name: INFLUXDB_ADMIN_PASSWORD
          value: pass123!
        volumeMounts:
          - name: influxdb-v1-volume
            mountPath: /var/lib/influxdb
      volumes:
        - name: influxdb-v1-volume
          persistentVolumeClaim:
            claimName: influxdb-v1-volume-claim



# Persisten Volume Example
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-v1-volume-claim
  namespace: infra
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb-v1
  namespace: infra
spec:
  selector:
    app: influxdb-v1
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086

---
#Create Chronograf
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chronograf
  namespace: infra
  labels:
    app: chronograf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chronograf
  template:
    metadata:
      labels:
        app: chronograf
    spec:
      containers:
      - name: chronograf
        image: chronograf:latest
        ports:
        - containerPort: 8888
        env:
## Fill in with Own settings
        - name: INFLUXDB_URL
          value: http://influxdb-v1.infra.svc.cluster.local:8086
        - name: INFLUXDB_USERNAME
          value: admin
        - name: INFLUXDB_PASSWORD
          value: pass123!
        volumeMounts:
          - name: chronograf-volume
            mountPath: /var/lib/chronograf
      volumes:
        - name: chronograf-volume
          persistentVolumeClaim:
            claimName: chronograf-volume-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chronograf-volume-claim
  namespace: infra
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: chronograf
  namespace: infra
spec:
  selector:
    app: chronograf
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
---