apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: archivy-config
  name: archivy-config
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
