apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: elasticsearch-data
  name: elasticsearch-data
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
