apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: unifi-unifi
  name: unifi-unifi
  namespace: infra
spec:
  storageClassName: synology
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: unifi-data
  name: unifi-data
  namespace: infra
spec:
  storageClassName: synology
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 32Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: unifi-backup
  name: unifi-backup
  namespace: infra
spec:
  storageClassName: synology
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 32Gi
