apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: synology
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: synology/nfs
parameters:
  archiveOnDelete: false
  onDelete: delete
