apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kanboard.simplefxn.com
  namespace: istio-system
spec:
  secretName: kanboard.simplefxn.com
  subject:
    organizations:
    - SimpleFxn
  commonName: kanboard.simplefxn.com
  dnsNames:
  - kanboard.simplefxn.com
  issuerRef:
    name: simplefxn-issuer
    kind: ClusterIssuer