---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kanboard
  namespace: apps  
spec:
  interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: kanboard
      version: 2.5.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    image:
      repository: kanboard/kanboard
      tag: v1.2.18
      pullPolicy: IfNotPresent
    service:
      main:
        enabled: true
        type: ClusterIP
        ports:
          http:
            enabled: true
            port: 80
    podLabels: 
      app: kanboard
    env:
      TZ: "America/Chicago"
    persistence:
    # -- enable data persistence
      data:
        enabled: false
        emptyDir:
          enabled: false
        mountPath: /var/www/app/data
        accessMode: ReadWriteOnce
        storageClass: synology
        size: 8Gi
