apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: home-assistant.simplefxn.com
  namespace: istio-system
spec:
  secretName: home-assistant.simplefxn.com
  subject:
    organizations:
    - SimpleFxn
  commonName: home-assistant.simplefxn.com
  dnsNames:
  - home-assistant.simplefxn.com
  issuerRef:
    name: simplefxn-issuer
    kind: ClusterIssuer