---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: vuegraf
  namespace: apps
spec:
  dependsOn:
    - name: influxdb
      namespace: infra
  interval: 10m0s
  path: ./overlays/prod/apps/vuegraf
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-k8s
    namespace: flux-system
  validation: client