---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: apps  
spec:
  interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: home-assistant
      version: 9.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    image:
      repository: homeassistant/home-assistant
      tag: 2021.6.3
      pullPolicy: IfNotPresent
    service:
      main:
        enabled: true
        type: ClusterIP
        ports:
          http:
            enabled: true
            port: 8123
    persistence:
      config:
        enabled: true
        storageClass: synology
        size: 8Gi
    prometheus:
      # -- Enable and configure a Prometheus serviceMonitor for the chart under this key.
      # @default -- See values.yaml
      serviceMonitor:
        enabled: false
        portName: http
        ## See https://www.home-assistant.io/docs/authentication/ for where to find
        ## long lived access token creation under your account profile, which is
        ## needed to monitor Home Assistant
        # bearerTokenSecret:
        #   name: ""
        #   key: ""
        # interval: 1m
        # additionalLabels: {}
    podLabels: 
      app: home-assistant
    env:
      TZ: "America/Chicago"
    influxdb:
      enabled: true
      architecture: standalone
      database: home_assistant
      authEnabled: false
      persistence:
        enabled: true
        storageClass: synology
        size: 16Gi
    