apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: home-assistant
  namespace: apps
  name: home-assistant-config
spec:
  storageClassName: synology
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi