apiVersion: v1
kind: Secret
metadata:
    name: secret-basic-auth
type: Opaque
data:
    password: ENC[AES256_GCM,data:bRS6Co4i+aM6,iv:z+YAXaKryk6PYpo06E+nSJkXOt5oi1xPortiAubV8Js=,tag:bAGaLB0FjODQ8Ax6BfAPRQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-09-02T04:45:37Z"
    mac: ENC[AES256_GCM,data:sUoBXs7u8FV2eDc/jkibbFcGUG4p2JiZcQUVnYPwl4uMk0bi+5NOvKgNJvCBp3uL3jGk4UqF9kcCEA+UVkeGBWLzigiH3FVPdJgsVDH4CKH4ocRW4nOPWwmWL1Owjmim2fzMkDK3lBJEpDrO7x416KnAg5GhmGTGtnTXoIrihNk=,iv:hDyKQVNfI+jvf6yyMywQrYRDrTnVKRUPUVbbosrTQu0=,tag:UuhbRRDCXzBOGD+NySELjA==,type:str]
    pgp:
        - created_at: "2021-09-02T04:45:36Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAx/NiVxbkaAhAQ//Up6uOdaaYLu9X73K9AezCnyNhZJnio7du57knJL9zP8D
            ZltaJ4Vg4If5DxULwiYdh/V902U3e68Qw58ExYTWN3r6WrzWVNeQTWUDWbAWuWlU
            4dkv0bUydzS+s43jko0/eVLT6CfHLQomu5V0jDw2IonaUyNgV4dNMQjJS6EZrVmN
            Peze1dzKCM6Aq+tCzuBjO3giQGYTeiE8aP/WIOCeEqNzcN3fgWH7hbfnIaWo3Kd8
            gV7rBYLS5XNuTbaj56eLaHNlSZYUJ0xErGMGJeflQXbqKAsm0nJU9O6CmxS4ZMQ1
            ZN+rlVXC9Uz6OlcgMHKcV64G6+/lvxT3GGq3Z2Yhq1Blea5IfheUxwoeHgus9u2U
            65isBu/+BL/j5m9g1WHkGCLEg62cBMnOS4u6iLp3g3RJF5RuEFQ46buA/sMALQRy
            zCmEEM/cVM6L9uR1IEkD9uMT/3jkMuJF2E1V7xnK5vuUa2j02qNM977rkvk9QXAc
            YDGOGGQT4XyNFMYsepyiyDiw2PS9xHY+5aJUPIW2Utohk6XhZhD5k+uWgHTapkyh
            QzZPHiDjPIVUBLi5v0OM0x4R5woqSAP9Br54HdPi+fnYa+MA6k89xhDFxjVBMBGH
            AZULX9LhNG9icoQI94hHDb3IPYexzIaTWuqhOm+UFAh1tcrAMo0MnHEL65neO0rU
            aAEJAhX+HwWEbLoUV2gh6w+M/ssK2VgYhL1M8reFdnCD9EUSssCK7Gsy7CDxoQFq
            gQ9Xd7gPWV26fhhlRbUiwT9ZKZxDCTgJ+GItV7p5xTAwjqxUWiJnachnZn1tXiPx
            1EyE8WgNpJG3
            =s8b7
            -----END PGP MESSAGE-----
          fp: 9DC11809DD7D102342B09932C40921F65EFEF866
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
