apiVersion: v1
kind: Service
metadata:
  name: home-assistant
  namespace: apps
spec:
  type: ClusterIP
  ports:
    - name: tcp
      port: 8123
      targetPort: 8123
    - name: tcp
      port: 8080
      targetPort: 8080
  selector:
    app.name: home-assistant
    app.instance: home-assistant
