apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cotoami.simplefxn.com
  namespace: istio-system
spec:
  secretName: cotoami.simplefxn.com
  subject:
    organizations:
    - SimpleFxn
  commonName: cotoami.simplefxn.com
  dnsNames:
  - cotoami.simplefxn.com
  issuerRef:
    name: simplefxn-issuer
    kind: ClusterIssuer