bases:
- environments.yaml
---
repositories:
  # Kubernetes incubator repo of helm charts
  - name: "mittwald"
    url: "https://helm.mittwald.de"

releases:
  - name: "kubernetes-secret-generator"
    chart: "mittwald/kubernetes-secret-generator"
    disableValidation: true
    namespace: {{ .Namespace }}
    version: {{ .Values.kubernetes_secrets_generator_chart_version | quote }}
    wait: true
    timeout: 300
    values:
    - {{ toYaml .Values.kubernetes_secrets_generator | nindent 6 }}