apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sabnzbd.simplefxn.com
  namespace: istio-system
spec:
  secretName: sabnzbd.simplefxn.com
  subject:
    organizations:
    - SimpleFxn
  commonName: sabnzbd.simplefxn.com
  dnsNames:
  - sabnzbd.simplefxn.com
  issuerRef:
    name: simplefxn-issuer
    kind: ClusterIssuer