prometheus_community_chart_version: "43.2.1"
k8s_raw_chart_version: "0.2.3"

prometheus:
  fullnameOverride: home-monitoring
  commonLabels: 
    prometheus.io/monitor: "true"
  grafana:
    serviceMonitor: 
      enabled: true
    persistence:
      enabled: true
      size: 16Gi
    admin:
      existingSecret: "grafana-creadentials"
      userKey: admin-user
      passwordKey: admin-password
  prometheus:
    prometheusSpec:
      retention: 365d
      serviceMonitorSelector:
        matchLabels:
          prometheus.io/monitor: "true"
      storageSpec:
        volumeClaimTemplate:
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 128Gi

