apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - serviceaccount.yaml
  - role.yaml
  - rolebinding.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - deployment.yaml
  - class.yaml
spec:
  dependsOn:
    - name: metallb-system
      namespace: infra