bases:
- environments.yaml
---
repositories:
  # Kubernetes incubator repo of helm charts
  - name: "incubator"
    url: "https://charts.helm.sh/incubator"

releases:
  - name: "rethinkdb"
    chart: "incubator/raw"
    namespace: {{ .Namespace }}
    version: {{ .Values.k8s_raw_chart_version | quote }}
    wait: true
    timeout: 60
    values:
    - resources:   
      - apiVersion: apps/v1
        kind: StatefulSet
        metadata:
          name: rethinkdb
        spec:
          replicas: 1
          selector: 
            matchLabels:
              app: rethinkdb
          serviceName: "rethinkdb"
          template:
            metadata:
              labels:
                app: rethinkdb
            spec:
              containers:
              - name: rethinkdb
                image: rethinkdb:latest
                imagePullPolicy: Always
                env:
                  - name: JOIN
                    value: rethinkdb-0
                ports:
                - name: web
                  containerPort: 8080
                  protocol: TCP
                - name: db
                  containerPort: 28015
                  protocol: TCP
                volumeMounts:
                - mountPath: "/data"
                  name: rethinkdb-data
          volumeClaimTemplates:
          - metadata:
              name: rethinkdb-data
            spec:
              accessModes:
                - ReadWriteOnce
              storageClassName: local
              volumeMode: Filesystem 
              resources:
                requests:
                  storage: 24Gi       
      - apiVersion: v1
        kind: Service
        metadata:
          name: rethinkdb
        spec:
          type: LoadBalancer
          selector:
            app: rethinkdb
          ports:
            - name: rethinkdb-admin
              protocol: TCP
              port: 8080
              targetPort: 8080
            - name: rethinkdb-cluster
              protocol: TCP
              port: 28015
              targetPort: 28015
