---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: deepstack
  namespace: apps  
spec:
  interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: deepstack
      version: 1.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    #
    # IMPORTANT NOTE
    #
    # This chart inherits from our common library chart. You can check the default values/options here:
    # https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
    #

    image:
      # -- image repository
      repository: deepquestai/deepstack
      # -- image tag
      tag: cpu
      # -- image pull policy
      pullPolicy: IfNotPresent

    # -- environment variables. See more environment variables in the [deepstack documentation](https://docs.deepstack.cc).
    # @default -- See below
    env:
      # -- Enable scene recognition
      VISION-SCENE: True
      # -- Enable face detection
      VISION-FACE: True
      # -- Enable object detection
      VISION-DETECTION: True
      # -- Protect detection and recognition APIs with a key
      # API-KEY: changeMe
      # -- Protect admin APIs (such as managing models) with a key
      # ADMIN-KEY: changeMe

    ui:
      # -- enable web UI
      enabled: true
      image:
        # -- image repository for ui
        repository: robmarkcole/deepstack-ui
        # -- image tag
        tag: latest
        # -- image pull policy
        pullPolicy: Always
      # -- environment variables. See more environment variables in the [deepstack-ui README](https://github.com/robmarkcole/deepstack-ui).
      # @default -- See below
      env:
      # - name: DEEPSTACK_TIMEOUT
      #   value: the timeout to wait for deepstack, default 30 seconds
      # - name: DEEPSTACK_CUSTOM_MODEL
      #  value: the name of a custom model, if you wish to use one
        - name: DEEPSTACK_UI_DEBUG_MODE
          value: True  # options `True` or `False` (default). Lowers the minimum confidence threshold to 1%
      ingress:
        # -- Enable and configure ingress settings for the chart under this key.
        # @default -- See values.yaml
        ui:
          enabled: true
          primary: true

    # -- Configures service settings for the chart.
    # @default -- See values.yaml
    service:
      main:
        ports:
          http:
            port: 5000

    # -- security context. May be necessary when using GPU image
    # @default -- See values.yaml
    securityContext: {}
      # privileged: true

    ingress:
      # -- Enable and configure ingress settings for the chart under this key.
      # @default -- See values.yaml
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"    
          cert-manager.io/cluster-issuer: "simplefxn-issuer"
        hosts:
        - host: deepstack.simplefxn.com
          paths:
          - path: /
            pathType: Prefix
        tls:
          - hosts:
            - "deepstack.simplefxn.com"
            secretName: deepstack-simplefxn-tls

    # -- Configure persistence settings for the chart under this key.
    # @default -- See values.yaml
    persistence: 
      data:
        enabled: true
        mountPath: /datastore
        type: pvc
        storageClass: local
        size: 64Gi
        accessMode: ReadWriteOnce
