---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nebula-studio
  namespace: nebula
spec:
  interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      git: git@github.com:vesoft-inc/nebula-studio.git
      ref: master
      path: deployment/helm
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: nebula-studio
      version: v3.0.0
  values:
    replicaCount: 1

    image:
      pullPolicy: IfNotPresent
      httpGateway:
        name: vesoft/nebula-http-gateway
        version: v2.1.1
      nebulaStudio:
        name: vesoft/nebula-graph-studio
        version: v3.1.0
      nginx:
        name: nginx
        version: alpine

    imagePullSecrets: []

    nameOverride: ""
    fullnameOverride: ""

    service:
      type: LoadBalancer
      port: 7001

    resources:
      httpGateway:
      nebulaStudio:
      nginx:

    persistent:
      storageClassName: ""
      size: 5Gi

    podAnnotations: {}

    nodeSelector: {}

    tolerations: []

    affinity: {}