apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaUser
metadata:
  name: ripe-user
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: ripe
          patternType: literal
        operation: Read
      - resource:
          type: topic
          name: ripe
          patternType: literal
        operation: Describe
      - resource:
          type: group
          name: ripe-group
          patternType: literal
        operation: Read