apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: ripe-user
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      # Example consumer Acls for topic ripe using consumer group ripe-group
      - resource:
          type: topic
          name: ripe
          patternType: literal
        operation: Read
        host: "*"
      - resource:
          type: topic
          name: ripe
          patternType: literal
        operation: Describe
        host: "*"
      - resource:
          type: group
          name: ripe-group
          patternType: literal
        operation: Read
        host: "*"
      # Example Producer Acls for topic ripe
      - resource:
          type: topic
          name: ripe
          patternType: literal
        operation: Write
        host: "*"
      - resource:
          type: topic
          name: ripe
          patternType: literal
        operation: Create
        host: "*"
      - resource:
          type: topic
          name: ripe
          patternType: literal
        operation: Describe
        host: "*"