---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cryptpad
  namespace: apps
spec:
  dependsOn:
    - name: nfs-synology
      namespace: infra
    - name: istio
      namespace: istio-system
  interval: 1m0s
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  path: ./overlays/prod/apps/cryptpad
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-k8s
    namespace: flux-system
  validation: client