{
 "title": "Energy Usage",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "account",
    "label": "Account",
    "query": "SHOW TAG VALUES FROM energy_usage WITH KEY = account_name"
   }
  ]
 },
 "panels": [
  {
   "title": "panelNameHere",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "panelNameHere",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "energy_usage",
     "select": [
      [
       { "params": [ "usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device_name", "operator": "=", "value": "panelNameHere" },
      { "condition": "AND", "key": "account_name", "operator": "=~", "value": "/^$account$/" }
     ]
    }
   ]
  },
  {
   "title": "Kiln",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Watts" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "energy_usage",
     "query": "SELECT mean(\"usage\") FROM \"energy_usage\" WHERE (\"device_name\" = 'Kiln') AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device_name", "operator": "=", "value": "Kiln" }
     ]
    }
   ]
  },
  {
   "title": "Split A/C Unit",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short", "label": "Watts" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "energy_usage",
     "select": [
      [
       { "params": [ "usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device_name", "operator": "=", "value": "Split AC" }
     ]
    }
   ]
  },
  {
   "title": "Active Circuit Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Watts" }
   ],
   "targets": [
    {
     "alias": "$tag_device_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device_name" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "energy_usage",
     "select": [
      [
       { "params": [ "usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "account_name", "operator": "=~", "value": "/^$account$/" },
      { "condition": "AND", "key": "device_name", "operator": "!=", "value": "panelNameHere" }
     ]
    }
   ]
  },
  {
   "title": "Shedroom",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Watts" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "energy_usage",
     "select": [
      [
       { "params": [ "usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device_name", "operator": "=", "value": "Shedroom" }
     ]
    }
   ]
  },
  {
   "title": "Combined Outlets and Lights",
   "type": "graph",
   "description": "math * 5 accounts for the five circuits being merged",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "Watts" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "energy_usage",
     "query": "SELECT mean(\"usage\") *5 FROM \"energy_usage\" WHERE (\"device_name\" =~ /Outlets|Lights/) AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*5" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "device_name", "operator": "=~", "value": "/Outlets|Lights/" }
     ]
    }
   ]
  }
 ]
}