kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: neo4j-noauth-volume-claim
  namespace: infra
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Gi
  storageClassName: synology