---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: frigate
  namespace: apps  
spec:
  interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: frigate
      version: 6.3.1
      sourceRef:
        kind: HelmRepository
        name: blakeblackshear
        namespace: flux-system
  values:
    # Default values for frigate.
    # This is a YAML-formatted file.
    # Declare variables to be passed into your templates.
    
    # -- upgrade strategy type (e.g. Recreate or RollingUpdate)
    strategyType: Recreate
    
    image:
      # -- Docker registry/repository to pull the image from
      repository: blakeblackshear/frigate
      # -- Overrides the default tag (appVersion) used in Chart.yaml ([Docker Hub](https://hub.docker.com/r/blakeblackshear/frigate/tags?page=1))
      tag: 0.10.1-amd64
      # -- Docker image pull policy
      pullPolicy: IfNotPresent
    
    # -- amount of shared memory to use for caching
    shmSize: 1Gi
    
    # -- frigate configuration - see [Docs](https://docs.frigate.video/configuration/index) for more info
    config: |
      mqtt:
        # Required: host name
        host: 172.20.20.19
        # Optional: port (default: shown below)
        port: 1883
        # Optional: topic prefix (default: shown below)
        # WARNING: must be unique if you are running multiple instances
        topic_prefix: frigate
        # Optional: client id (default: shown below)
        # WARNING: must be unique if you are running multiple instances
        client_id: frigate
        # Optional: user
        # user: mqtt_user
        # Optional: password
        # NOTE: Environment variables that begin with 'FRIGATE_' may be referenced in {}.
        #       eg. password: '{FRIGATE_MQTT_PASSWORD}'
        # password: password
        # Optional: interval in seconds for publishing stats (default: shown below)
        stats_interval: 60
    
      detectors:
        # coral:
        #   type: edgetpu
        #   device: usb
        cpu1:
          type: cpu
        cpu2:
          type: cpu
        cpu3:
          type: cpu
        cpu4:
          type: cpu
    
      cameras:
        # Name of your camera
        front_door:
          ffmpeg:
            inputs:
              - path: rtsp://root:Ike0cuso@172.23.0.186/axis-media/ssm/media.amp?resolution=1920x1080
                roles:
                  - detect
                  - rtmp
            input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport udp_multicast -stimeout 5000000 -use_wallclock_as_timestamps 1
          detect:
            width: 1280
            height: 720
            fps: 5
    
    # Probes configuration
    probes:
      liveness:
        enabled: true
        initialDelaySeconds: 30
        failureThreshold: 5
        timeoutSeconds: 10
      readiness:
        enabled: true
        initialDelaySeconds: 30
        failureThreshold: 5
        timeoutSeconds: 10
      startup:
        enabled: false
        failureThreshold: 30
        periodSeconds: 10
    
    persistence:
      data:
        # -- Enables persistence for the data directory
        enabled: false
        ## frigate data Persistent Volume Storage Class
        ## If defined, storageClassName: <storageClass>
        ## If set to "-", storageClassName: "", which disables dynamic provisioning
        ## If undefined (the default) or set to null, no storageClassName spec is
        ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
        ##   GKE, AWS & OpenStack)
        ##
        # storageClass: "-"
        ##
        ## If you want to reuse an existing claim, you can pass the name of the PVC using
        ## the existingClaim variable
        # existingClaim: your-claim
        # subPath: some-subpath
    
        # -- [access mode](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes) to use for the PVC
        accessMode: ReadWriteOnce
    
        # -- size/capacity of the PVC
        size: 10Gi
    
        # -- Do not delete the pvc upon helm uninstall
        skipuninstall: false
        