apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: bedrock
  namespace: apps
  labels:
    k8s-app: bedrock
spec:
  selector:
    matchLabels:
      name: bedrock
  template:
    metadata:
      labels:
        name: bedrock
    spec:
      hostNetwork: true
      tolerations:
      # these tolerations are to have the daemonset runnable on control plane nodes
      # remove them if your control plane nodes should not run pods
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      initContainers:
        - name: init
          image: ubuntu:18.04
          command: [ "/bin/sh", "-c", "/script/test.sh" ]
          volumeMounts:
            - mountPath: /data
              name: bedrock-data
            - name: bedrock-init-script
              mountPath: /script
          env:
          - name: EULA
            value: "TRUE"
          - name: DEBUG
            value: "TRUE"
      containers:
        - name: main
          image: ubuntu:18.04
          imagePullPolicy: Always
          command: ["/bin/sleep", "3650d"]
          volumeMounts:
            - mountPath: /data
              name: bedrock-data
          ports:
            - containerPort: 19132
              protocol: UDP
          tty: true
          stdin: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      volumes:
      - name: bedrock-data
        persistentVolumeClaim:
          claimName: bds
      - name: bedrock-init-script
        configMap:
          name: bedrock-init-script
          defaultMode: 0777
  