---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft-bedrock
  namespace: apps
spec:
  interval: 5m
  chart:
    spec:
      chart: minecraft-bedrock
      version: 2.0.0
      sourceRef:
        kind: HelmRepository
        name: minecraft-server
        namespace: flux-system
      interval: 5m
  values:
    image: itzg/minecraft-bedrock-server
    imageTag: latest

    extraEnv:
      TZ: America/Chicago

    persistence:
      storageClass: local
      dataDir:
        enabled: true
        Size: 10Gi

    resources:
      requests:
        memory: 512Mi
        cpu: 500m

    minecraftServer:
      eula: "TRUE"
      version: "LATEST"
      difficulty: normal
      gameMode: survival
      levelSeed: "1"
      SERVER_PORT: "19232"
      ops: "2535435538046181"
      levelName: "TNT World"
      maxThreads: 0 # Maximum number of threads the server tries to use. If set to 0 or removed then it uses as many as possible.
      cheats: true
      serverName: "Ketelburg"
      serviceType: LoadBalancer

