---
apiVersion: v1
kind: Service
metadata:
  name: bds
  namespace: apps
spec:
  selector:
    app: bds
  ports:
    - port: 19132
      protocol: UDP
  ipFamily: IPv4
  # Use LoadBalancer if running on a provider that supports that
#  type: LoadBalancer
  # or use NodePort on a non-managed system;
  # however, you'll need to lookup port assigned to the service
  type: NodePort