apiVersion: v1
kind: ConfigMap
metadata:
  name: bedrock-init-script
  namespace: apps
data:
  server.properties: |
    #!/bin/bash
    set -eo pipefail

    : "${TMP_DIR:=/tmp}"

    if [[ ${DEBUG^^} = TRUE ]]; then
      set -x
      curlArgs=(-v)
      echo "DEBUG: running as $(id -a) with $(ls -ld /data)"
      echo "       current directory is $(pwd)"
    fi
