---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: bds
  name: bds
  namespace: apps
spec:
  # never more than 1 since BDS is not horizontally scalable
  replicas: 1
  serviceName: bds
  selector:
    matchLabels:
      app: bds
  template:
    metadata:
      labels:
        app: bds
    spec:
      containers:
        - name: main
          image: itzg/minecraft-bedrock-server
          imagePullPolicy: Always
          env:
          - name: EULA
            value: "TRUE"
          volumeMounts:
            - mountPath: /data
              name: data
          ports:
            - containerPort: 19132
              protocol: UDP
          readinessProbe: &probe
            exec:
              command:
                - mc-monitor
                - status-bedrock
                - --host
                # force health check against IPv4 port
                - 127.0.0.1
            initialDelaySeconds: 30
          livenessProbe: *probe
          tty: true
          stdin: true
        - name: vscode
          image: codercom/code-server:3.11.1
          imagePullPolicy: IfNotPresent
          workingDir: /config
          args:
            - --port=8124
            - --extensions-dir=/config/.vscode
            - --user-data-dir=/config/.vscode
          ports:
            - name: vscode
              containerPort: 8124
              protocol: TCP
          env:
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vscode-secret
                  key: password
          volumeMounts:
            - mountPath: /data
              name: bedrock-data
          securityContext:
              runAsUser: 0
  volumeClaimTemplates:
    - metadata:
        name: bedrock-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
---