bases:
- environments.yaml
---
repositories:
  # Kubernetes incubator repo of helm charts
  - name: "incubator"
    url: "https://charts.helm.sh/incubator"

releases:
  - name: "nats"
    chart: "incubator/raw"
    namespace: {{ .Namespace }}
    version: {{ .Values.k8s_raw_chart_version | quote }}
    wait: true
    timeout: 60
    values:
    - resources:
      - apiVersion: "nats.io/v1alpha2"
        kind: "NatsCluster"
        metadata:
          name: "nats"
        spec:
          size: 3
          natsConfig:
            debug: true
            trace: true