apiVersion: v1
kind: Service
metadata:
  name: redis-noauth
  namespace: infra
spec:
  selector:
    app: redis-noauth
  ports:
  - port: 6379
    targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-noauth
  namespace: infra
  labels:
    app: redis-noauth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-noauth
  template:
    metadata:
      labels:
        app: redis-noauth
    spec:
      containers:
      - name: master
        image: redis
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379