bases:
- environments.yaml
---
repositories:
  - name: camelk
    url: https://apache.github.io/camel-k/charts/

releases:
  - name: "stack"
    chart: "camelk/camel-k"
    disableValidation: true
    namespace: {{ .Namespace }}
    version: {{ .Values.camelk_chart_version | quote }}
    wait: true
    timeout: 300
    values:
    - {{ toYaml .Values.camelk | nindent 6 }}
   