apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana.simplefxn.com
  namespace: istio-system
spec:
  secretName: grafana.simplefxn.com
  subject:
    organizations:
    - SimpleFxn
  commonName: grafana.simplefxn.com
  dnsNames:
  - grafana.simplefxn.com
  issuerRef:
    name: simplefxn-issuer
    kind: ClusterIssuer