bases:
- environments.yaml
---
repositories:
  - name: rocketchat
    url: https://rocketchat.github.io/helm-charts
  # Kubernetes incubator repo of helm charts
  - name: "incubator"
    url: "https://charts.helm.sh/incubator"

releases:
  - name: "rocketchat"
    chart: "rocketchat/rocketchat"
    disableValidation: true
    namespace: {{ .Namespace }}
    version: {{ .Values.rocket_chat_chart_version | quote }}
    wait: true
    timeout: 300
    values:
    - {{ toYaml .Values.rocket_chat | nindent 6 }}
 