apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homer.simplefxn.com
  namespace: istio-system
spec:
  secretName: homer.simplefxn.com
  subject:
    organizations:
    - SimpleFxn
  commonName: homer.simplefxn.com
  dnsNames:
  - homer.simplefxn.com
  issuerRef:
    name: simplefxn-issuer
    kind: ClusterIssuer