---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-red
  namespace: apps  
spec:
  interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: node-red
      version: 9.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    image:
      repository: nodered/node-red
      tag: latest
      pullPolicy: IfNotPresent
    service:
      main:
        enabled: true
        type: ClusterIP
        ports:
          http:
            enabled: true
            port: 1880
    podLabels: 
      app: node-red
    env:
      TZ: "America/Chicago"
      # -- filepath for persistance
      STORAGE_FILEPATH: "/config"
      # -- sets backend
      STORAGE_TYPE: "file"
    persistence:
      config:
        enabled: true
        storageClass: synology
        size: 4Gi