apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: paperless.simplefxn.com
  namespace: istio-system
spec:
  secretName: paperless.simplefxn.com
  subject:
    organizations:
    - SimpleFxn
  commonName: paperless.simplefxn.com
  dnsNames:
  - paperless.simplefxn.com
  issuerRef:
    name: simplefxn-issuer
    kind: ClusterIssuer