---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: mosquitto
  namespace: infra
spec:
  interval: 10m0s
  path: ./overlays/prod/infra/apps/mosquitto
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-k8s
    namespace: flux-system