---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: postgres
  namespace: infra
spec:
  dependsOn:
    - name: nfs-synology
  interval: 1m0s
  path: ./overlays/prod/infra/apps/postgres
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-k8s
    namespace: flux-system
  validation: client
  force: true