apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nebula.simplefxn.com
  namespace: istio-system
spec:
  secretName: nebula.simplefxn.com
  subject:
    organizations:
    - SimpleFxn
  commonName: nebula.simplefxn.com
  dnsNames:
  - nebula.simplefxn.com
  issuerRef:
    name: simplefxn-issuer
    kind: ClusterIssuer