---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nebula-studio
  namespace: infra
spec:
  interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: ./deployment/helm
      sourceRef:
        kind: GitRepository
        name: nebula-studio-git
        namespace: infra
  values:
    replicaCount: 1
    image:
      pullPolicy: IfNotPresent
      httpGateway:
        name: vesoft/nebula-http-gateway
        version: v2.1.1
      nebulaStudio:
        name: vesoft/nebula-graph-studio
        version: v3.1.0
      nginx:
        name: nginx
        version: alpine
    imagePullSecrets: []
    auth:
      existingSecret: influx-auth
    nameOverride: ""
    fullnameOverride: ""
    service:
      type: ClusterIP
      port: 7001
    resources:
      httpGateway:
      nebulaStudio:
      nginx:
    persistent:
      storageClassName: ""
      size: 5Gi
    podAnnotations: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}