redis_chart_version: "9.1.4"
k8s_raw_chart_version: "0.2.3"

redis:
  existingSecret: "redis-credentials"
  existingSecretPasswordKey: "password"
  persistence:
    size: 32Gi
  redis:
    externalAccess:
      enabled: true
  cluster:
    nodes: 3
    replicas: 2
  metrics:
    enabled: true
