redis_chart_version: "8.3.5"
k8s_raw_chart_version: "0.2.3"

redis:
  existingSecret: "redis-creadentials"
  existingSecretPasswordKey: "password"
  persistence:
    storageClass: "local"
    size: 128Gi
  redis:
    externalAccess:
      enabled: true
      annotations:
          azure-load-balancer-internal: "true"
  cluster:
    nodes: 9
    replicas: 2
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true 
      labels:
        prometheus.io/monitor: "true"
