redis_chart_version: "18.6.2"
k8s_raw_chart_version: "0.2.3"

redis:
  clusterDomain: subject86.com
  auth:
    existingSecret: "redis-credentials"
    existingSecretPasswordKey: "password"
  master:
    count: 1
    persistence:
      size: 16Gi
  replica:
    replicaCount: 1
    persistence:
      size: 16Gi
  service:
    type: ClusterIP
  
